package features

var TitleHTTPServers = []string{
	"ALL HTTP SERVERS",
    "ALLHTTPSERVERS",
    "ALL CREATING HTTP SERVERS",
    "ALLCREATINGHTTPSERVERS",
}


var OriginalHTTPServers = DataBase{
	Alldatafield: `
ALL HTTP SERVERS
ALL HTTP SERVERS
ALL HTTP SERVERS
ALL HTTP SERVERS`,
}